### PR TITLE
some stuff for the roster

### PR DESCRIPTION
**Pull request by jjs0sbw**

### CODE REVIEW

**Comment by jjs0sbw** [comment]
Added another change to this pull request, just for practice...

Lets see how this works

**Comment by jjs0sbw** [comment]
Some more practice with push to origin master and pull requests

**Comment by jjs0sbw** [comment]
Just pushed from a repo on a linux box.. looks good so far..

**Comment by reneedv** [comment]
Hi Joe,
  The other pushes came through to your pull request. Since I don't want to merge those in, I'll close this PR and just add you to the roster manually.
Thanks!
**R

**Comment by jjs0sbw** [comment]
Renee:

Thanks...

I am just trying to get a feel for how this all works....

Is there a 'lint' program for Ruby like JSLint or C lint?

Take care, be good to yourself and have fun,

Joe

On Fri, Oct 3, 2014 at 2:11 PM, Renée Hendricksen notifications@github.com
wrote:

> Hi Joe,
> The other pushes came through to your pull request. Since I don't want to
> merge those in, I'll close this PR and just add you to the roster manually.
> Thanks!
> **R
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UWE-Ruby/RubyFall2014/pull/13#issuecomment-57861915.

## 

Joe Simpson
_"All that is gold does not glitter,__Not all those who wander are lost;__The
old that is strong does not wither,_
_Deep roots are not reached by the frost."  J. R.R. Tolkien_

**Comment by reneedv** [comment]
Hi Joe,
  Yes there is a Ruby styleguide linter called RuboCop:  https://github.com/bbatsov/rubocop

**Comment by jjs0sbw** [comment]
Cool...

Thanks..

On Fri, Oct 3, 2014 at 2:22 PM, Renée Hendricksen notifications@github.com
wrote:

> Hi Joe,
> Yes there is a Ruby styleguide linter called RuboCop:
> https://github.com/bbatsov/rubocop
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/UWE-Ruby/RubyFall2014/pull/13#issuecomment-57864219.

## 

Joe Simpson
_"All that is gold does not glitter,__Not all those who wander are lost;__The
old that is strong does not wither,_
_Deep roots are not reached by the frost."  J. R.R. Tolkien_

**Pull request closed without merging**
